name: Build Project 6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Project 6
        run: make -C project6

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: project6-build
          path: project6/bin/
